FROM gradle:7.1.1-jdk11 AS build
ARG VERSION
COPY --chown=gradle:gradle . /home/gradle/src/
WORKDIR /home/gradle/src
RUN gradle :transport-service:build -Pversion=${VERSION} --no-daemon


FROM openjdk:11
EXPOSE 8111
ARG VERSION
COPY --from=build /home/gradle/src/transport-service/build/libs/transport-service-${VERSION}.jar reeco-transport.jar

CMD ["java","-jar","reeco-transport.jar"]