version: '3.9'

# Define services
services:
  # App backend service
  reecotechservices:
    build:
      context: .
      dockerfile: dockerfile-all-in-one
      args:
        VERSION: 0.1.0
    environment:
      CASSANDRA_KEYSPACE: ${CASSANDRA_KEYSPACE}
      CASSANDRA_USER: ${CASSANDRA_USER}
      CASSANDRA_PASSWORD: ${CASSANDRA_PASSWORD}
      CASSANDRA_CONTACT_POINTS: ${CASSANDRA_CONTACT_POINTS}
      CASSANDRA_PORT: ${CASSANDRA_PORT}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_TS_EVENT_GROUP_ID: ${KAFKA_TS_EVENT_GROUP_ID}
      KAFKA_CONFIG_EVENT_GROUP_ID: ${KAFKA_CONFIG_EVENT_GROUP_ID}
      KAFKA_CONFIG_AUTO_OFFSET_RESET: ${KAFKA_CONFIG_AUTO_OFFSET_RESET}
      KAFKA_TS_EVENT_AUTO_OFFSET_RESET: ${KAFKA_TS_EVENT_AUTO_OFFSET_RESET}
      KAFKA_MAX_CONCURRENCY: ${KAFKA_MAX_CONCURRENCY}
      KAFKA_TS_EVENT_TOPIC_PARTITIONS: ${KAFKA_TS_EVENT_TOPIC_PARTITIONS}
      KAFKA_TS_EVENT_TOPIC_REPLICATIONS: ${KAFKA_TS_EVENT_TOPIC_REPLICATIONS}
      KAFKA_CONFIG_TOPIC_PARTITIONS: ${KAFKA_CONFIG_TOPIC_PARTITIONS}
      KAFKA_CONFIG_TOPIC_REPLICATIONS: ${KAFKA_CONFIG_TOPIC_REPLICATIONS}
      KAFKA_ALARM_TOPIC_PARTITIONS: ${KAFKA_ALARM_TOPIC_PARTITIONS}
      KAFKA_ALARM_TOPIC_REPLICATIONS: ${KAFKA_ALARM_TOPIC_REPLICATIONS}
      KAFKA_ALARM_NOTI_TOPIC_PARTITIONS: ${KAFKA_ALARM_NOTI_TOPIC_PARTITIONS}
      KAFKA_ALARM_NOTI_TOPIC_REPLICATIONS: ${KAFKA_ALARM_NOTI_TOPIC_REPLICATIONS}
      KAFKA_CONFIG_EVENT_HTTP_GROUP_ID: ${KAFKA_CONFIG_EVENT_HTTP_GROUP_ID}
    restart: always
    network_mode: host
#    ports:
#      - 8986:8986
#      - 7001:7001
#      - 8043:8043