FROM gradle:7.1.1-jdk11 AS build
ARG VERSION
COPY --chown=gradle:gradle . /home/gradle/src/
WORKDIR /home/gradle/src
RUN gradle :core:build -Pversion=${VERSION} --no-daemon



FROM openjdk:11
EXPOSE 7001

COPY --from=build /home/gradle/src/core/build/libs/core-0.1.0.jar reeco-core.jar

CMD ["java","-jar","reeco-core.jar"]