FROM gradle:7.1.1-jdk11 AS build
ARG VERSION
COPY --chown=gradle:gradle . /home/gradle/src/
WORKDIR /home/gradle/src
RUN gradle :ingestion-service:build -Pversion=${VERSION} --no-daemon

FROM openjdk:11
ARG VERSION
EXPOSE 8086

COPY --from=build /home/gradle/src/ingestion-service/build/libs/ingestion-service-${VERSION}.jar reeco-ingestion-service.jar

CMD ["java","-jar","reeco-ingestion-service.jar"]