FROM gradle:7.1.1-jdk11 AS build
COPY --chown=gradle:gradle . /home/gradle/src/
WORKDIR /home/gradle/src
RUN gradle :config-service:build --no-daemon


FROM openjdk:11
ARG VERSION
EXPOSE 8986

COPY --from=build /home/gradle/src/config-service/build/libs/config-service-${VERSION}.jar reeco-config-service.jar



CMD ["java","-jar","reeco-config-service.jar"]