version: '3.0'

services:
  transport:
    build: .
    image: arihub/transport-service
    mem_limit: 500m
    environment:
      - KAFKA_BOOTSTRAP_SERVER=localhost:29092

    volumes:
      - ../data:/data
      - ../logs:/logs
    restart: always
    network_mode: host

