version: '3.9'

# Define services
services:
  # App backend service
  configservice:
    build:
      context: config-service
      dockerfile: Dockerfile
      args:
        VERSION: 0.1.0
    ports:
      - "8986:8986"
    cpus: 1
    restart: always
    network_mode: host

  ingestionservice:
    build:
      context: ingestion-service
      dockerfile: Dockerfile
      args:
        VERSION: 0.1.0
    ports:
      - "8086:8086"
    cpus: 2
    restart: always
    network_mode: host
