version: '3.9'
services:
  httptransportservice:
    image: arihub/transport-http-service:v3_23.04.02_01
    environment:
      CASSANDRA_KEYSPACE: ${CASSANDRA_KEYSPACE}
      CASSANDRA_USER: ${CASSANDRA_USER}
      CASSANDRA_PASSWORD: ${CASSANDRA_PASSWORD}
      CASSANDRA_CONTACT_POINTS: ${CASSANDRA_CONTACT_POINTS}
      CASSANDRA_PORT: ${CASSANDRA_PORT}
      KAFKA_CONFIG_EVENT_GROUP_ID: ${KAFKA_CONFIG_EVENT_HTTP_GROUP_ID}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
      KAFKA_CONFIG_AUTO_OFFSET_RESET: ${KAFKA_CONFIG_AUTO_OFFSET_RESET}
    restart: always
    network_mode: host

